"""
06_generate_sql_pdf.py
------------------------
Runs all 20 SQL queries against the SQLite database and generates a PDF
showing each query alongside a preview of its actual output. This is the
"proof of work" PDF for the SQL portion of the project — every result
shown here was generated by actually executing the query, not typed by hand.
"""

import sqlite3
import re
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                  TableStyle, PageBreak, HRFlowable)
from reportlab.lib.enums import TA_CENTER

conn = sqlite3.connect("../data/northbridge_hr.db")
cur = conn.cursor()

with open("../sql/hr_analysis_queries.sql") as f:
    content = f.read()

content_no_block = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
chunks = content_no_block.split(';')

queries = []
for chunk in chunks:
    lines = chunk.split('\n')
    title_lines = [l.replace('--', '').strip() for l in lines
                   if l.strip().startswith('--') and re.match(r'--\s*\d+\.', l.strip())]
    sql_lines = [l for l in lines if not l.strip().startswith('--') and l.strip()]
    sql = '\n'.join(sql_lines).strip()
    if sql:
        queries.append((title_lines[0] if title_lines else "Query", sql))

assert len(queries) == 20, f"Expected 20 queries, found {len(queries)}"

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="TitleCustom", fontSize=22, leading=26,
                           alignment=TA_CENTER, textColor=colors.HexColor("#1F3864"),
                           spaceAfter=10, fontName="Helvetica-Bold"))
styles.add(ParagraphStyle(name="SubtitleCustom", fontSize=11, leading=15,
                           alignment=TA_CENTER, textColor=colors.HexColor("#666666"),
                           spaceAfter=20))
styles.add(ParagraphStyle(name="QTitle", fontSize=11.5, leading=15,
                           textColor=colors.HexColor("#1F3864"),
                           spaceBefore=4, spaceAfter=6, fontName="Helvetica-Bold"))
styles.add(ParagraphStyle(name="SQLCode", fontSize=7.6, leading=10,
                           fontName="Courier", textColor=colors.HexColor("#222222"),
                           backColor=colors.HexColor("#F4F6FA"),
                           borderPadding=6, spaceAfter=8))
styles.add(ParagraphStyle(name="ResultLabel", fontSize=8.5, leading=11,
                           textColor=colors.HexColor("#777777"),
                           fontName="Helvetica-Oblique", spaceAfter=4))

doc = SimpleDocTemplate("../reports/SQL_Queries_Results.pdf", pagesize=letter,
                         topMargin=0.6*inch, bottomMargin=0.6*inch,
                         leftMargin=0.6*inch, rightMargin=0.6*inch)

story = []
story.append(Spacer(1, 0.6*inch))
story.append(Paragraph("Northbridge Health Group", styles["TitleCustom"]))
story.append(Paragraph("SQL Query Portfolio — 20 Queries with Live Results",
                        styles["SubtitleCustom"]))
story.append(Paragraph(
    "Database: northbridge_hr.db (SQLite) &nbsp;|&nbsp; Tables: employees, "
    "compensation, performance &nbsp;|&nbsp; All queries executed and verified "
    "against the actual database.", styles["SubtitleCustom"]))
story.append(HRFlowable(width="100%", thickness=0.75, color=colors.HexColor("#CCCCCC")))
story.append(Spacer(1, 0.2*inch))

def escape_html(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))

for i, (title, sql) in enumerate(queries, 1):
    cur.execute(sql.rstrip(';'))
    col_names = [d[0] for d in cur.description]
    rows = cur.fetchall()
    preview_rows = rows[:6]

    story.append(Paragraph(escape_html(title), styles["QTitle"]))

    sql_html = escape_html(sql).replace("\n", "<br/>")
    story.append(Paragraph(sql_html, styles["SQLCode"]))

    story.append(Paragraph(
        f"Result preview ({len(rows)} total row{'s' if len(rows) != 1 else ''}, showing first {len(preview_rows)}):",
        styles["ResultLabel"]))

    table_data = [col_names] + [[str(c) if c is not None else "NULL" for c in r] for r in preview_rows]
    n_cols = len(col_names)
    col_width = min(1.3*inch, (7.3*inch) / n_cols)
    t = Table(table_data, colWidths=[col_width]*n_cols, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2E5395")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 6.8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F5FA")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t)
    story.append(Spacer(1, 14))

    if i % 3 == 0 and i != len(queries):
        story.append(PageBreak())

doc.build(story)
conn.close()
print("SQL results PDF generated -> ../reports/SQL_Queries_Results.pdf")
